### ISSUE TITLE
Docs - Bad hyperlink

### ISSUE THREAD

**Issue by santaimpersonator** [sparkfun/SparkFun_u-blox_SAM-M10Q#2]
There is an incorrect product link in this [section](https://docs.sparkfun.com/SparkFun_u-blox_SAM-M10Q/hardware_overview/#plated-through-hole-headers) of the hardware overview:
![image](https://github.com/sparkfun/SparkFun_u-blox_SAM-M10Q/assets/36016723/9e3357ab-c6cc-46ea-8ca9-9d38cd2aedb4)

Looks like the link just needs to be added here:
https://github.com/sparkfun/SparkFun_u-blox_SAM-M10Q/blob/d886846b7572d3635691e711028dcbe2416bee81/docs/hardware_overview.md?plain=1#L188C172-L188C188

### Expected behavior
Should link to product: https://www.sparkfun.com/products/15096

### Actual behavior
Links to page: https://docs.sparkfun.com/SparkFun_u-blox_SAM-M10Q/hardware_overview/

**Comment by bboyho** [comment]
Merged the docs branch and updated the link. The markdown to link the product was empty so it defaulted to pointing back to the page. =)
